### ISSUE TITLE
vdr_pi travis failures: pita

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#107]
I have disabled travis ubuntu arm64 it does not work at all.
The other two raspbian armhf are almost as bad.
I will not be restarting them any longer and may disable those too.
https://github.com/rgleason/vdr_pi/tree/frontend1-update

**Comment by bdbcat** [comment]
Rick...
Are these build problems, or run-time problem?
Where are the build logs?
Dave

**Comment by rgleason** [comment]
Run time for the first two armhf and they will complete.
Build for arm64.

I think these scripts have become performance problems.. They worked before. Jon has struggled with this too, but his scripts seem to work better right now. 
https://github.com/jongough/testplugin_pi/blob/master/.travis.yml
https://github.com/jongough/testplugin_pi/tree/master/ci  see the .travis * sh

Failure of the travis scripts is frequent.
---
I have been moving the code to the master branch today and made some changes to
Deployment: to  opencpn/vdr-prod,  opencpn/vdr-beta, opencpn/vdr-alpha
(As a member of the OpenCPN Organization Team, you and others can also use these repositories.)

I also made some changes so version is entered in Cmakelists.txt
https://github.com/rgleason/vdr_pi/commits/master
again one travis failed. I have arm64 commented out.

**Comment by bdbcat** [comment]
Talking about VDR only...
What are the run-time problems with VDR on raspbian builds?
Dave

**Comment by rgleason** [comment]
Reruns have a chance of completing with these failures.
1. Completion.
2. Not having files available 
3.  Time

Arm64 does not work for vdr and is commented out now.

**Comment by bdbcat** [comment]
Rick...
I see that the Travis build bot is flakey.  So we live with it.
What I am asking is:  What run-time problems are you having with VDR?
Dave

**Comment by bdbcat** [comment]
Also, please start a job with ARM64 Travis build enabled, so that I can help you with the error.

btw, you can always restart a failed job on Travis, without penalty.  I have to do it frequently, as the travis bots are, indeed, flakey.

Thanks
Dave

**Comment by rgleason** [comment]
Yes, I do restart often and multiple times. 
Tomorrow night I will renable arm64 and double check its code.
Should I refer to oesenc?  or head towards Jon's approach?

**Comment by rgleason** [comment]
VDR_pi issues? None in Windows and Ubuntu once I turn off all plugins.

**Comment by bdbcat** [comment]
Rick...
An hour ago you said:
"Run time probblems for the first two armhf "
I guess you mean build problems.  Yes, the builds take a long time.  And sometimes the bot fails.
I'm trying to find out what your problems are, so I can help...

**Comment by bdbcat** [comment]
Rick...
For ARM64, you should look at oeSENC.  I'm not even sure that Jon is building for ARM64 yet...

**Comment by rgleason** [comment]
ok, thankyou.  Have turned it back on.

**Comment by bdbcat** [comment]
Rick...
The entry in .travis.yml should look like this:

```
  - env:
    - OCPN_TARGET=bionic-arm64
    - OCPN_BRANCH=master
    - DOCKER_IMAGE=arm64v8/ubuntu:18.04
    services:
    - docker
    script:
    - "./ci/travis-build-ubuntu-arm64.sh"

```
And NOT like this:
```

- env:
    - OCPN_TARGET=bionic-arm64
    - OCPN_BRANCH=master
    - DOCKER_IMAGE=arm64v8/ubuntu:18.04
    services:
    - docker
    script:
    - chmod a+x
    - "./ci/travis-build-ubuntu-arm64.sh"
    - travis_wait 40 sleep infinity & bash ./ci/travis-build-raspbian-armhf.sh


```
