### ISSUE TITLE
ocpn-plugins.xml update process broken

### ISSUE THREAD

**Issue by jongough** [OpenCPN/plugins#130]
The process for updating the ocpn-plugins.xml was dodgy at best when it was first introduced, but is now becoming unworkable. As more plugins move to the new Plugin Manager process the ability to maintain this file will decrease to the point where most people will give up trying.

Each commit/pull request for an update is based on the 'current' master, but if two or more pull requests are available to be merged the first will succeed the others will fail with conflicts in the ocpn-plugins.xml file. This requires the owners of the other pull requests to close their current pull request, delete their branch completely, pull the lastest version of master, reapply all their additions and deletions of files, recreate the ocpn-plugins.xml file, create a new pull request then hope that no-one else is doing updates at the same time or they will have to redo the whole process again.

Each update currently requires downloading 14 xml files from cloudsmith for each plugin as individual downloads (there is no 'mass' download capability). This rapidly gets frustrating in the extreme if the above process has to be followed multiple times. I know I can save stuff around, but it is a very manual process. There MUST be a better way of building the ocpn-plugins.xml file after the merge of a pull request that adds/deletes xml files such that it is always consistent.

**Comment by rgleason** [comment]
I agree Jon, as the file gets bigger it is going to take longer and longer checking all the xml and urls.

Also it is very manual, downloading the metadata and adding it to the plugins/metadata folder, building the new file and checking all xml and urls and then making a PR.

I was thinking today about making a script or batch file that downloads the correct xml files from cloudsmith to a default directory. This is possible using wget I think and using a search somehow in cloudsmith. 

Since I am now using the OpenCPN organization repository and since everything is "public"  I can use "https://cloudsmith.io/~opencpn/repos/"  and adding the plugin info
- "https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/"
- Then we need to be able to search for "[version number]*metadata"
- For example: 
https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.5.19*metadata

Which produces a list of 15 xml files.  Next they have to be download to some convenient specific location to be added to the plugins/metadata file.

I think the checking of xml files is problematic because I still do not get a list of files that have bad urls or are mal formed.  It requires manually cutting and pasting batches of xml file into a temp folder and running the check again until the culprit is isolated. This is not efficient and is a great waste of time.

Consequently I do not intend to do this very much.!

**Comment by bdbcat** [comment]
Jon...
Did you read and try this:

Jon...
It is always safe to delete an ocpn-plugins.xml file from your local copy, and regenerate from a freshly pulled github master, with your metadata updated. Probably much quicker than manually fixing the conflicts. Like this:

    rm ocpn-plugins.xml
    git pull origin master
    Update your plugin metadata, by whatever means you use.
    tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml --force
    Commit this state.
    git push origin master

Dave

**Comment by bdbcat** [comment]
I agree that there could be better tooling for this process.  But I would not call the current process "broken".  Just sometimes inconvenient..

**Comment by bdbcat** [comment]
Scripting the Cloudsmith download using wget in a loop, and forming the file names from the known git commit SHA suffix is one way, and works well for me.

**Comment by jongough** [comment]
You obviously don't use it like a plugin developer (hardly surprising since you control this). From the developer point of view it is an exercise in frustration. 

The real problem is that pulls frequently invalidate other pulls. So I put up a pull against the master and it all passed OK and got the green light. However, you accepted another pull before mine which then invalidated my pull which you then asked me to fix up. This suggests that the whole update process for ocpn-plugins.xml is very fragile and needs fixing up. There is a possibility that adding a main.yml fie to the '.github/workflows' directory that has something like this:
```
# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
```
to cause the generation of the ocpn-plugins.xml file may be a solution.
