### ISSUE TITLE
New Circleci Android Docker images - current being deprecated.

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#956]
[Legacy Convenience Image Deprecation](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034)

...designed to be faster, more efficient, and most importantly, more reliable. You can learn more about all of the features [on our blog post 933](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/). As we begin to deprecate the legacy images, this document provides information on the migration process.

**All legacy images have a Docker namespace of circleci, while next-gen images have a Docker namespace of cimg.** For example, migrating from the legacy Ruby or Python image to the respective next-gen image can be done as follows:

circleci/ruby:2.3.0 → cimg/ruby:2.3.0
circleci/python:3.8.4 → cimg/python:3.8.4

Images available now

https://circleci.com/developer/images

At the top of the list there is:

cimg/android | An  Android Docker image built to run on CircleCI that contains API levels,  build & platform tools, and the NDK variant images. | 2023.08

[cimg/android](https://circleci.com/developer/images/image/cimg/android)
	
[An Android Docker image built to run on CircleCI that contains API levels, build & platform tools, and the NDK variant images.](https://circleci.com/developer/images/image/cimg/android)
	
[2023.08](https://circleci.com/developer/images/image/cimg/android)

@bdbcat   Shouldn't we be using this to build Android now?

We currently are using a docker image

```
    build-android-arm64:
        docker:
        - image: cimg/android:2021.10.2-ndk
        resource_class: large
        environment:
        - OCPN_TARGET:  android-arm64
        - DEPLOY_USE_ORB: true
```

and

```
    build-android-armhf:
        docker:
        - image: cimg/android:2021.10.2-ndk
        resource_class: large
        environment:
        - OCPN_TARGET:  android-armhf
```
