### ISSUE TITLE
CircleCI Notice: MacOS 

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#994]
Update all macos projects using "medium" resource before Oct 2

Update the **resource class** key in your configuration file from medium to **macos.x86.medium.gen2**. in the next 30 days. 

> This is a reminder to update any projects using the macOS medium resource before October 2nd, 2023 to avoid a build error. Please update the resource class key in your configuration file from medium to macos.x86.medium.gen2. in the next 30 days. You are receiving this email because you are associated with a project that has used the medium macOS resource in the last six months.

**Comment by rgleason** [comment]
TP Template has

OpenCPN 5.6.2

```
    build-macos:
        macos:
            xcode: "12.5.1"
        resource_class: macos.x86.medium.gen2   <---OK
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 312                              <----Shouldn't this be 315 Now??????
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code
```

OpenCPN 5.8
```
    build-macos-wx32:
        macos:
            xcode: "12.5.1"
        resource_class: macos.x86.medium.gen2   <----OK
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 32
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code

```
